import curatedData from "@/data/locations.json";

export interface Location {
  name: string;
  country: string;
  iata: string;
  /** Airport name or alternate names, searched but shown as a subtitle. */
  note?: string;
  /** State, province or region, e.g. "California". */
  region?: string;
}

/** Row format of data/airports.json (generated by scripts/build-airports.mjs). */
type AirportRow = [place: string, airport: string, iata: string, country: string, region: string];

/**
 * Popular places, ordered roughly by how commonly they are picked. They are always available and
 * shown first; the full airport list (about 4,000) loads on demand and is merged in after them.
 */
const curated: Location[] = curatedData.locations;

let all: Location[] = curated;
let loaded = false;
let loading: Promise<Location[]> | null = null;

function merge(rows: AirportRow[]): Location[] {
  // Copies, because popular places get enriched below. Several can share an airport (Kerala and Kochi).
  const result = curated.map((l) => ({ ...l }));
  const names = new Set(result.map((l) => l.name.toLowerCase()));
  const byIata = new Map<string, Location[]>();
  for (const l of result) byIata.set(l.iata, [...(byIata.get(l.iata) ?? []), l]);

  for (const [place, airport, iata, country, region] of rows) {
    const known = byIata.get(iata);
    if (known) { // enrich popular places with region and airport name so "california" finds LAX
      for (const l of known) {
        l.region ??= region;
        l.note ??= airport;
      }
      continue;
    }
    // Names must be unique so a chosen value maps back to one airport (e.g. "Chicago · MDW").
    let name = place;
    if (names.has(name.toLowerCase())) name = `${place} · ${iata}`;
    names.add(name.toLowerCase());
    byIata.set(iata, []);
    result.push({ name, country, iata, note: airport, region });
  }
  return result;
}

/** Loads the full airport list once (a separate chunk, fetched the first time it is needed). */
export function loadAllLocations(): Promise<Location[]> {
  loading ??= import("@/data/airports.json").then((m) => {
    all = merge(m.default as AirportRow[]);
    loaded = true;
    return all;
  });
  return loading;
}

export const isFullListLoaded = () => loaded;

const SPECIAL: Record<string, string> = { "ø": "o", "æ": "ae", "œ": "oe", "ß": "ss", "đ": "d", "ł": "l", "ı": "i", "þ": "th" };

/** Lower-cases and strips accents so "Reykjavík" and "Tromsø" match "reykjavik" and "tromso". */
const norm = (s: string) =>
  s.trim().toLowerCase().normalize("NFD").replace(/\p{M}/gu, "").replace(/[øæœßđłıþ]/g, (c) => SPECIAL[c]);

export function findLocation(text: string): Location | undefined {
  const t = norm(text);
  if (!t) return undefined;
  return all.find((l) => norm(l.name) === t) ?? all.find((l) => norm(l.iata) === t);
}

/** Airport code for a known place name or code; "" when unknown. */
export const toIata = (text: string): string => findLocation(text)?.iata ?? "";

const COUNTRY_ALIASES: Record<string, string> = {
  usa: "united states", us: "united states", america: "united states",
  uk: "united kingdom", england: "united kingdom", britain: "united kingdom",
  uae: "united arab emirates", korea: "south korea",
};

/** Lower score = better match. */
function score(l: Location, q: string): number | null {
  const name = norm(l.name);
  const note = norm(l.note ?? "");
  const region = norm(l.region ?? "");
  const country = norm(l.country);
  const iata = norm(l.iata);
  const countryQ = COUNTRY_ALIASES[q] ?? q;
  const words = name.split(/[\s,·()/-]+/);
  if (name === q) return 0;
  if (iata === q) return 1;
  if (COUNTRY_ALIASES[q] && country === COUNTRY_ALIASES[q]) return 1; // "usa", "uk", "uae"
  if (name.startsWith(q) || words.includes(q)) return 2;
  if (words.some((w) => w.startsWith(q)) || iata.startsWith(q)) return 3;
  if (name.includes(q)) return 4;
  if (note.includes(q) || region.startsWith(q) || country.startsWith(countryQ)) return 5;
  if (region.includes(q) || country.includes(countryQ)) return 6;
  return null;
}

export function searchLocations(query: string, limit = 8): Location[] {
  const q = norm(query);
  if (!q) return all.slice(0, limit);
  return all
    .map((l, order) => ({ l, order, s: score(l, q) }))
    .filter((x): x is { l: Location; order: number; s: number } => x.s !== null)
    .sort((a, b) => a.s - b.s || a.order - b.order)
    .slice(0, limit)
    .map((x) => x.l);
}

export const getAllLocations = () => all;
