// Generates src/domain/iconNodes.ts from lucide-react (ISC) so the PDF draws the same icons as the UI.
// Run: node scripts/build-icons.mjs   (after `npm install`). Add an icon by adding it to ICONS.
import fs from "node:fs";

// app icon key -> lucide icon file name
const ICONS = {
  plane: "plane", hotel: "hotel", bed: "bed", car: "car", coffee: "coffee", utensils: "utensils", moon: "moon",
  landmark: "landmark", ticket: "ticket", ship: "ship", bus: "bus", train: "train-front", walk: "footprints",
  route: "route", bike: "bike", clock: "clock", parking: "square-parking",
};

const out = {};
for (const [key, file] of Object.entries(ICONS)) {
  const m = await import(new URL(`../node_modules/lucide-react/dist/esm/icons/${file}.mjs`, import.meta.url));
  out[key] = m.__iconData.node.map(([tag, attrs]) => {
    const { key: _k, ...rest } = attrs;
    return [tag, rest];
  });
}
fs.writeFileSync(
  new URL("../src/domain/iconNodes.ts", import.meta.url),
  `// Generated by scripts/build-icons.mjs from lucide-react (ISC license). Do not edit by hand.
export type IconNode = [tag: string, attrs: Record<string, string | number>][];
export const ICON_NODES: Record<string, IconNode> = ${JSON.stringify(out, null, 2)};
`,
);
console.log(`Wrote ${Object.keys(out).length} icons`);
